spring.application.name=fintech
spring.datasource.url=jdbc:postgresql://localhost:5432/animalfly?currentSchema=animals
spring.datasource.username=postgres
spring.datasource.password=schef2002
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.user=postgres
spring.flyway.password=schef2002
spring.flyway.default-schema=animals