animal-starter:
  animal:
    catNames: barsik,persik
    fishNames: nemo,goldie
    wolfNames: rex,buddy
    bearNames: fluffy,thumper

psql-connect:
  base-data:
    user: postgres
    password: schef2002
    dataBaseURL: jdbc:postgresql://localhost:5432/animalbase