CREATE TABLE animals.animal (
    id integer NOT NULL,
    birth_date date,
    "character" character varying(255),
    cost numeric(19,2),
    name character varying(255),
    type integer,
    breed integer
);


ALTER TABLE animals.animal OWNER TO postgres;

--
-- Name: animal_id_seq; Type: SEQUENCE; Schema: animals; Owner: postgres
--

ALTER TABLE animals.animal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME animals.animal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: animal_type; Type: TABLE; Schema: animals; Owner: postgres
--

CREATE TABLE animals.animal_type (
    id_type integer NOT NULL,
    is_wild boolean NOT NULL,
    type character varying(255)
);


ALTER TABLE animals.animal_type OWNER TO postgres;

--
-- Name: animal_type_animal_list; Type: TABLE; Schema: animals; Owner: postgres
--

CREATE TABLE animals.animal_type_animal_list (
    animal_type_id_type integer NOT NULL,
    animal_list_id integer NOT NULL
);


ALTER TABLE animals.animal_type_animal_list OWNER TO postgres;

--
-- Name: animal_type_id_type_seq; Type: SEQUENCE; Schema: animals; Owner: postgres
--

ALTER TABLE animals.animal_type ALTER COLUMN id_type ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME animals.animal_type_id_type_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: animals_habitats; Type: TABLE; Schema: animals; Owner: postgres
--

CREATE TABLE animals.animals_habitats (
    id_animal_type integer NOT NULL,
    id_area integer NOT NULL
);


ALTER TABLE animals.animals_habitats OWNER TO postgres;

--
-- Name: animals_provider; Type: TABLE; Schema: animals; Owner: postgres
--

CREATE TABLE animals.animals_provider (
    id_animal_type integer NOT NULL,
    id_provider integer NOT NULL
);


ALTER TABLE animals.animals_provider OWNER TO postgres;

--
-- Name: animalshabitats; Type: TABLE; Schema: animals; Owner: postgres
--

CREATE TABLE animals.animalshabitats (
    id_animal_type integer,
    id_area integer
);


ALTER TABLE animals.animalshabitats OWNER TO postgres;

--
-- Name: breed; Type: TABLE; Schema: animals; Owner: postgres
--

CREATE TABLE animals.breed (
    id integer NOT NULL
);


ALTER TABLE animals.breed OWNER TO postgres;

--
-- Name: breed_id_seq; Type: SEQUENCE; Schema: animals; Owner: postgres
--

ALTER TABLE animals.breed ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME animals.breed_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE animals.habitats (
    id_area integer NOT NULL,
    area character varying(255)
);


ALTER TABLE animals.habitats OWNER TO postgres;

--
-- Name: provider; Type: TABLE; Schema: animals; Owner: postgres
--

CREATE TABLE animals.provider (
    id_provider integer NOT NULL,
    name character varying(255),
    phone character varying(255)
);


ALTER TABLE animals.provider OWNER TO postgres;